name: Sync oci-help Image

on:
  workflow_dispatch: # 支持手动点击运行

permissions:
  packages: write
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and Push
        run: |
          SOURCE="gz1903/oci-help:latest"
          TARGET="ghcr.io/${{ github.repository_owner }}/oci-help:latest"
          TARGET=$(echo "$TARGET" | tr '[:upper:]' '[:lower:]')
          
          docker pull $SOURCE
          docker tag $SOURCE $TARGET
          docker push $TARGET
